spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
    sql: debug
    org:
      springframework:
        web: debug

  file:
    name: logs/log.txt

server:
  port: ${SERVER_PORT}
