spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

security:
  jwt:
    secret-key: 1b3e9a48f82fb349124e988a104a8fa9efa3a1cbf61de7701958b59be1e7655f
    expiration-time: 3600000

logging:
  level:
    root: info
    sql: debug
    org:
      springframework:
        web: debug

  file:
    name: logs/log.txt

server:
  port: ${SERVER_PORT}
