spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

logging:
  level:
    root: info
    sql: debug
    org:
      springframework:
        web: debug

  file:
    name: vehicle_service_spring_v2/logs/log

server:
  port: ${SERVER_PORT}
